version: "2"

services:
  auth:
    build:
      context: ..
      dockerfile: ./Docker/auth.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - http
  mock_signer:
    build:
      context: ..
      dockerfile: ./Docker/mock_signer.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - http
  bitcoin_scanner:
    build:
      context: ..
      dockerfile: ./Docker/bitcoin_scanner.dockerfile
    volumes:
      - ../src:/poet/src
    networks:
      - queue
  claims-to-db:
    build:
      context: ..
      dockerfile: ./Docker/claims_to_db.dockerfile
    networks:
      - queue
      - db
  explorer:
    build:
      context: ..
      dockerfile: ./Docker/explorer.dockerfile
    volumes:
      - ../src:/poet/src
    networks:
      - db
      - outside
  torrent_system:
    build:
      context: ..
      dockerfile: ./Docker/torrent_system.dockerfile
    volumes:
      - ../src:/poet/src
    networks:
      - queue
      - http
  trusted_publisher:
    build:
      context: ..
      dockerfile: ./Docker/trusted_publisher.dockerfile
    volumes:
      - ../src:/poet/src
    networks:
      - queue
      - http
  rabbitmq:
    image: library/rabbitmq
    networks:
      - queue
  db:
    build:
      context: ..
      dockerfile: ./poet_db.dockerfile
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - db
  nginx:
    build:
      context: ..
      dockerfile: ./nginx.dockerfile
    volumes:
      - ./letsencrypt:/etc/letsencrypt/
    networks:
      - http
    expose:
      - "80:80"
      - "443:443"

networks:
  db:
    internal: true
  queue:
    internal: true
  http:
    internal: true
  outside:
    driver: bridge
