version: "2"

services:
  auth:
    build:
      context: ..
      dockerfile: ./Docker/auth.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - http
  mock-signer:
    build:
      context: ..
      dockerfile: ./Docker/mock-signer.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - http
  bitcoin-scanner:
    build:
      context: ..
      dockerfile: ./Docker/bitcoin-scanner.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - queue
  claims-to-db:
    build:
      context: ..
      dockerfile: ./Docker/claims-to-db.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - queue
      - db
  explorer:
    build:
      context: ..
      dockerfile: ./Docker/explorer.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - db
      - outside
  torrent-system:
    build:
      context: ..
      dockerfile: ./Docker/torrent-system.dockerfile
    volumes:
      - ../node/src:/poet/src
      - ../node/torrents:/poet/torrents
    networks:
      - queue
      - http
  trusted-publisher:
    build:
      context: ..
      dockerfile: ./Docker/trusted-publisher.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - queue
      - http
  rabbitmq:
    image: library/rabbitmq
    networks:
      - queue
  db:
    build:
      context: ..
      dockerfile: ./Docker/db.dockerfile
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - db
  nginx:
    build:
      context: ..
      dockerfile: ./Docker/nginx.dockerfile
    networks:
      - outside
      - http
    expose:
      - "80"
      - "443"

networks:
  db:
    internal: true
  queue:
    internal: true
  http:
    internal: true
  outside:
    driver: bridge
