version: "2"

services:
  bitcoin_scanner:
    build:
      context: ..
      dockerfile: ./Docker/bitcoin_scanner.dockerfile
    volumes:
      - ../src:/poet/src
    networks:
      - queue
  claims-to-db:
    build:
      context: ..
      dockerfile: ./Docker/claims_to_db.dockerfile
    networks:
      - queue
      - db
  explorer:
    build:
      context: ..
      dockerfile: ./Docker/explorer.dockerfile
    volumes:
      - ../src:/poet/src
    networks:
      - db
      - outside
    expose:
      - "3050:3050"
  torrent_system:
    build:
      context: ..
      dockerfile: ./Docker/torrent_system.dockerfile
    volumes:
      - ../src:/poet/src
    networks:
      - db
      - outside
    expose:
      - "3050:3050"
  db:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - db

networks:
  db:
    internal: true
  queue:
    internal: true
  outside:
    driver: bridge
