version: "2"

services:
  auth:
    build:
      context: ..
      dockerfile: ./Docker/auth.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - http
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"
  mock-signer:
    build:
      context: ..
      dockerfile: ./Docker/mock-signer.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - http
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"
  bitcoin-scanner:
    build:
      context: ..
      dockerfile: ./Docker/bitcoin-scanner.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - queue
      - outside
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"
  claims-to-db:
    build:
      context: ..
      dockerfile: ./Docker/claims-to-db.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - queue
      - db
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"
  explorer:
    build:
      context: ..
      dockerfile: ./Docker/explorer.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - db
      - http
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"
  torrent-system:
    build:
      context: ..
      dockerfile: ./Docker/torrent-system.dockerfile
    volumes:
      - ../node/src:/poet/src
      - ../node/torrents:/poet/torrents
    networks:
      - queue
      - http
      - outside
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"
  trusted-publisher:
    build:
      context: ..
      dockerfile: ./Docker/trusted-publisher.dockerfile
    volumes:
      - ../node/src:/poet/src
    networks:
      - queue
      - http
      - outside
    depends_on:
      - explorer
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"
  rabbitmq:
    build:
      context: ..
      dockerfile: ./Docker/queue.dockerfile
    networks:
      - queue
    hostname: rabbitmq
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"
  db:
    build:
      context: ..
      dockerfile: ./Docker/db.dockerfile
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - db
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"
  nginx:
    build:
      context: ..
      dockerfile: ./Docker/nginx-staging.dockerfile
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - outside
      - http
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"
  web:
    build:
      context: ..
      dockerfile: ./Docker/web.dockerfile
    volumes:
      - ../web/src:/web/src
    networks:
      - http
    log_driver: "json-file"
    log_opt:
      max-size: "100k"
      max-file: "20"

networks:
  db:
    internal: true
  queue:
    internal: true
  http:
    internal: true
  outside:
    driver: bridge
